/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentCreate
 */
export interface AttachmentCreate {
    /**
     * 
     * @type {string}
     * @memberof AttachmentCreate
     */
    attachType: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentCreate
     */
    fileId: string;
}

/**
 * Check if a given object implements the AttachmentCreate interface.
 */
export function instanceOfAttachmentCreate(value: object): value is AttachmentCreate {
    if (!('attachType' in value) || value['attachType'] === undefined) return false;
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function AttachmentCreateFromJSON(json: any): AttachmentCreate {
    return AttachmentCreateFromJSONTyped(json, false);
}

export function AttachmentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'attachType': json['attach_type'],
        'fileId': json['file_id'],
    };
}

export function AttachmentCreateToJSON(json: any): AttachmentCreate {
    return AttachmentCreateToJSONTyped(json, false);
}

export function AttachmentCreateToJSONTyped(value?: AttachmentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attach_type': value['attachType'],
        'file_id': value['fileId'],
    };
}

