/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * scheme for validating user login request data
 * @export
 * @interface AuthDataRefresh
 */
export interface AuthDataRefresh {
    /**
     * 
     * @type {string}
     * @memberof AuthDataRefresh
     */
    refresh: string;
}

/**
 * Check if a given object implements the AuthDataRefresh interface.
 */
export function instanceOfAuthDataRefresh(value: object): value is AuthDataRefresh {
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    return true;
}

export function AuthDataRefreshFromJSON(json: any): AuthDataRefresh {
    return AuthDataRefreshFromJSONTyped(json, false);
}

export function AuthDataRefreshFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthDataRefresh {
    if (json == null) {
        return json;
    }
    return {
        
        'refresh': json['refresh'],
    };
}

export function AuthDataRefreshToJSON(json: any): AuthDataRefresh {
    return AuthDataRefreshToJSONTyped(json, false);
}

export function AuthDataRefreshToJSONTyped(value?: AuthDataRefresh | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh': value['refresh'],
    };
}

