/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * scheme for validating user login request data
 * @export
 * @interface AuthDataBasic
 */
export interface AuthDataBasic {
    /**
     * 
     * @type {string}
     * @memberof AuthDataBasic
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDataBasic
     */
    password: string;
}

/**
 * Check if a given object implements the AuthDataBasic interface.
 */
export function instanceOfAuthDataBasic(value: object): value is AuthDataBasic {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthDataBasicFromJSON(json: any): AuthDataBasic {
    return AuthDataBasicFromJSONTyped(json, false);
}

export function AuthDataBasicFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthDataBasic {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function AuthDataBasicToJSON(json: any): AuthDataBasic {
    return AuthDataBasicToJSONTyped(json, false);
}

export function AuthDataBasicToJSONTyped(value?: AuthDataBasic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

