/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelCreate
 */
export interface ChannelCreate {
    /**
     * 
     * @type {string}
     * @memberof ChannelCreate
     */
    serverId: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ChannelCreate interface.
 */
export function instanceOfChannelCreate(value: object): value is ChannelCreate {
    if (!('serverId' in value) || value['serverId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ChannelCreateFromJSON(json: any): ChannelCreate {
    return ChannelCreateFromJSONTyped(json, false);
}

export function ChannelCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'serverId': json['server_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ChannelCreateToJSON(json: any): ChannelCreate {
    return ChannelCreateToJSONTyped(json, false);
}

export function ChannelCreateToJSONTyped(value?: ChannelCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'server_id': value['serverId'],
        'title': value['title'],
        'description': value['description'],
    };
}

