/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Datamodel with test channel data
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    channelId: string;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    serverId: string;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Channel
     */
    description?: string | null;
    /**
     * 
     * @type {any}
     * @memberof Channel
     */
    logo?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof Channel
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Channel interface.
 */
export function instanceOfChannel(value: object): value is Channel {
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('serverId' in value) || value['serverId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ChannelFromJSON(json: any): Channel {
    return ChannelFromJSONTyped(json, false);
}

export function ChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Channel {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'],
        'serverId': json['server_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ChannelToJSON(json: any): Channel {
    return ChannelToJSONTyped(json, false);
}

export function ChannelToJSONTyped(value?: Channel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
        'server_id': value['serverId'],
        'title': value['title'],
        'description': value['description'],
        'logo': value['logo'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

