/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';

/**
 * Dataclass with channel message data
 * 
 * *sequence is a serial number of the message in the text channel
 * @export
 * @interface ChannelMessage
 */
export interface ChannelMessage {
    /**
     * 
     * @type {Message}
     * @memberof ChannelMessage
     */
    message: Message;
    /**
     * 
     * @type {string}
     * @memberof ChannelMessage
     */
    channelId: string;
    /**
     * 
     * @type {number}
     * @memberof ChannelMessage
     */
    sequence: number;
}

/**
 * Check if a given object implements the ChannelMessage interface.
 */
export function instanceOfChannelMessage(value: object): value is ChannelMessage {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('sequence' in value) || value['sequence'] === undefined) return false;
    return true;
}

export function ChannelMessageFromJSON(json: any): ChannelMessage {
    return ChannelMessageFromJSONTyped(json, false);
}

export function ChannelMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'message': MessageFromJSON(json['message']),
        'channelId': json['channel_id'],
        'sequence': json['sequence'],
    };
}

export function ChannelMessageToJSON(json: any): ChannelMessage {
    return ChannelMessageToJSONTyped(json, false);
}

export function ChannelMessageToJSONTyped(value?: ChannelMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': MessageToJSON(value['message']),
        'channel_id': value['channelId'],
        'sequence': value['sequence'],
    };
}

