/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelUpdate
 */
export interface ChannelUpdate {
    /**
     * 
     * @type {string}
     * @memberof ChannelUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChannelUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ChannelUpdate interface.
 */
export function instanceOfChannelUpdate(value: object): value is ChannelUpdate {
    return true;
}

export function ChannelUpdateFromJSON(json: any): ChannelUpdate {
    return ChannelUpdateFromJSONTyped(json, false);
}

export function ChannelUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ChannelUpdateToJSON(json: any): ChannelUpdate {
    return ChannelUpdateToJSONTyped(json, false);
}

export function ChannelUpdateToJSONTyped(value?: ChannelUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

