/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageUpdate
 */
export interface MessageUpdate {
    /**
     * 
     * @type {string}
     * @memberof MessageUpdate
     */
    content?: string | null;
}

/**
 * Check if a given object implements the MessageUpdate interface.
 */
export function instanceOfMessageUpdate(value: object): value is MessageUpdate {
    return true;
}

export function MessageUpdateFromJSON(json: any): MessageUpdate {
    return MessageUpdateFromJSONTyped(json, false);
}

export function MessageUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function MessageUpdateToJSON(json: any): MessageUpdate {
    return MessageUpdateToJSONTyped(json, false);
}

export function MessageUpdateToJSONTyped(value?: MessageUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

