/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentCreate } from './AttachmentCreate';
import {
    AttachmentCreateFromJSON,
    AttachmentCreateFromJSONTyped,
    AttachmentCreateToJSON,
    AttachmentCreateToJSONTyped,
} from './AttachmentCreate';

/**
 * 
 * @export
 * @interface MessageCreate
 */
export interface MessageCreate {
    /**
     * 
     * @type {string}
     * @memberof MessageCreate
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageCreate
     */
    replyMessageId?: string | null;
    /**
     * 
     * @type {Array<AttachmentCreate>}
     * @memberof MessageCreate
     */
    attachments?: Array<AttachmentCreate> | null;
}

/**
 * Check if a given object implements the MessageCreate interface.
 */
export function instanceOfMessageCreate(value: object): value is MessageCreate {
    return true;
}

export function MessageCreateFromJSON(json: any): MessageCreate {
    return MessageCreateFromJSONTyped(json, false);
}

export function MessageCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'replyMessageId': json['reply_message_id'] == null ? undefined : json['reply_message_id'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(AttachmentCreateFromJSON)),
    };
}

export function MessageCreateToJSON(json: any): MessageCreate {
    return MessageCreateToJSONTyped(json, false);
}

export function MessageCreateToJSONTyped(value?: MessageCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'reply_message_id': value['replyMessageId'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(AttachmentCreateToJSON)),
    };
}

