/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerUpdate
 */
export interface ServerUpdate {
    /**
     * 
     * @type {string}
     * @memberof ServerUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServerUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ServerUpdate interface.
 */
export function instanceOfServerUpdate(value: object): value is ServerUpdate {
    return true;
}

export function ServerUpdateFromJSON(json: any): ServerUpdate {
    return ServerUpdateFromJSONTyped(json, false);
}

export function ServerUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ServerUpdateToJSON(json: any): ServerUpdate {
    return ServerUpdateToJSONTyped(json, false);
}

export function ServerUpdateToJSONTyped(value?: ServerUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

