/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerCreate
 */
export interface ServerCreate {
    /**
     * 
     * @type {string}
     * @memberof ServerCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServerCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ServerCreate interface.
 */
export function instanceOfServerCreate(value: object): value is ServerCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ServerCreateFromJSON(json: any): ServerCreate {
    return ServerCreateFromJSONTyped(json, false);
}

export function ServerCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ServerCreateToJSON(json: any): ServerCreate {
    return ServerCreateToJSONTyped(json, false);
}

export function ServerCreateToJSONTyped(value?: ServerCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

