/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * scheme for validating user login request data
 * @export
 * @interface TokenSet
 */
export interface TokenSet {
    /**
     * 
     * @type {string}
     * @memberof TokenSet
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof TokenSet
     */
    refresh: string;
}

/**
 * Check if a given object implements the TokenSet interface.
 */
export function instanceOfTokenSet(value: object): value is TokenSet {
    if (!('access' in value) || value['access'] === undefined) return false;
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    return true;
}

export function TokenSetFromJSON(json: any): TokenSet {
    return TokenSetFromJSONTyped(json, false);
}

export function TokenSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenSet {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function TokenSetToJSON(json: any): TokenSet {
    return TokenSetToJSONTyped(json, false);
}

export function TokenSetToJSONTyped(value?: TokenSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access': value['access'],
        'refresh': value['refresh'],
    };
}

