/* tslint:disable */
/* eslint-disable */
/**
 * Phialka
 * Phialka server REST API
 *
 * The version of the OpenAPI document: MVP v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInvite
 */
export interface UserInvite {
    /**
     * 
     * @type {string}
     * @memberof UserInvite
     */
    userId: string;
}

/**
 * Check if a given object implements the UserInvite interface.
 */
export function instanceOfUserInvite(value: object): value is UserInvite {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserInviteFromJSON(json: any): UserInvite {
    return UserInviteFromJSONTyped(json, false);
}

export function UserInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInvite {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function UserInviteToJSON(json: any): UserInvite {
    return UserInviteToJSONTyped(json, false);
}

export function UserInviteToJSONTyped(value?: UserInvite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

